joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
  
four_wheel_steering_controller:
  type        : "four_wheel_steering_controller/FourWheelSteeringController"
  front_wheel: ['source_fl_wheel', 'source_fr_wheel']
  rear_wheel: ['source_rl_wheel', 'source_rr_wheel']
  front_steering: ['source_fl_steering_wheel', 'source_fr_steering_wheel']
  rear_steering: ['source_rl_steering_wheel', 'source_rr_steering_wheel']
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  cmd_vel_timeout: 1.0 # not tested here

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  # wheel_separation : 0.122
  wheel_separation_h : 0.36
  wheel_separation_w : 0.34317
  wheel_radius : 0.1
  wheel_steering_y_offset : -0.1
  # wheel_steering_x_offset : 0.03

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier    : 1.0
  
  # Base frame_id
  # base_frame_id: base_footprint #default: base_link
  base_frame_id: base_link

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.667  # m/s
      min_velocity           : -1.667 # m/s
      has_acceleration_limits: true
      max_acceleration       : 1.0  # m/s^2
      min_acceleration       : -1.0 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 3.14  # rad/s
      min_velocity           : -3.14
      has_acceleration_limits: true
      max_acceleration       : 1.0  # rad/s^2
      min_acceleration       : -1.0 