bed_trolley:
  gazebo_ros_control:
    pid_gains:
      bed_fl_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      bed_fr_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      bed_rl_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      bed_rr_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      bed_fl_wheel:
        p: 1.0
        i: 0.01
        d: 0.1
      bed_fr_wheel:
        p: 1.0
        i: 0.01
        d: 0.1
      bed_rl_wheel:
        p: 1.0
        i: 0.01
        d: 0.1
      bed_rr_wheel:
        p: 1.0
        i: 0.01
        d: 0.1 