xray_detector:
  gazebo_ros_control:
    pid_gains:
      detector_fl_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      detector_fr_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      detector_rl_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      detector_rr_steering_wheel:
        p: 1000.0
        i: 0.1
        d: 10.0
      detector_fl_wheel:
        p: 1.0
        i: 0.01
        d: 0.1
      detector_fr_wheel:
        p: 1.0
        i: 0.01
        d: 0.1
      detector_rl_wheel:
        p: 1.0
        i: 0.01
        d: 0.1
      detector_rr_wheel:
        p: 1.0
        i: 0.01
        d: 0.1 