xray_detector:
  gazebo_ros_control:
    pid_gains:
      fl_steering_wheel:
        p: 50000.0
        i: 1
        d: 0.001
      fr_steering_wheel:
        p: 50000.0
        i: 1
        d: 0.001
      rl_steering_wheel:
        p: 50000.0
        i: 1
        d: 0.001
      rr_steering_wheel:
        p: 50000.0
        i: 1
        d: 0.001
      fl_wheel:
        p: 10.0
        i: 1
        d: 0.0
      fr_wheel:
        p: 10.0
        i: 1
        d: 0.0
      rl_wheel:
        p: 10.0
        i: 1
        d: 0.0
      rr_wheel:
        p: 10.0
        i: 1
        d: 0.0 